### ISSUE TITLE
Make UV-CDAT startup faster

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/VisTrails#75]
Meta-issue to track startup slowdowns.
- [X] Remove VTK package (scans VTK to generate VisTrails modules that are not used) (#1166)
- [ ] ESGF does HTTP requests during startup ([comment](https://github.com/UV-CDAT/uvcdat/issues/1232#issuecomment-95982508))
- [ ] A VCS canvas is created by the `UVCDATMainWindow` ([comment](https://github.com/UV-CDAT/uvcdat/issues/1232#issuecomment-95987083))

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1232
